[package]
name = "RustIOUringActor"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11.1"
tokio = { version = "1.43.0", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7.3"
libc = "0.2.167"

[dev-dependencies]
tempfile = "3.15.0"
